/*
 * This source file was generated by the Gradle 'init' task
 */
package org.gradle.declarative.lsp

import org.eclipse.lsp4j.launch.LSPLauncher

fun main() {
    val languageServer = DeclarativeLanguageServer()

    val launcher = LSPLauncher.createServerLauncher(
        languageServer,
        System.`in`,
        System.out
    )
    val remoteProxy = launcher.remoteProxy
    languageServer.connect(remoteProxy)

    // Start the language server
    val listening = launcher.startListening()
    System.err.println("Gradle Declartive Language Server: started")
    // Wait until the language server is stopped
    listening.get()
    System.err.println("Gradle Declartive Language Server: stopped")
}