name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
      - name: Execute Gradle build
        run: ./gradlew build

  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}