name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true
      - name: Execute Gradle build
        run: ./gradlew build

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: gradle/actions/setup-gradle@v4
      with:
        validate-wrappers: true
    - name: Package farJar
      run: ./gradlew :lsp:shadowJar
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./lsp/build/libs"
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4